" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimfiles/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim80/vimrc_example.vim or the vim manual
" and configure vim to your own liking!

" do not load defaults if ~/.vimrc is missing
"let skip_defaults_vim=1

if has('gui_running')
	set guioptions -=m 
	set guioptions -=T
endif

set encoding=utf-8
set fileencoding=utf-8

set list
function! SetDynamicListChars()
    " Disable 'list' and exit if the buffer is not modifiable or writable
    if !&l:modifiable || filewritable(expand('%:p')) != 1
        setlocal nolist
        return
    endif

    " Enable 'list' for writable files
    setlocal list

    " Fallback to tabstop if shiftwidth is set to 0 (default in Vim)
    let l:sw = &shiftwidth == 0 ? &tabstop : &shiftwidth
    let &l:listchars = 'trail:·,tab:│ ,multispace:┆' . repeat(' ', l:sw - 1)
endfunction

augroup DynamicListChars
    autocmd!
    autocmd OptionSet shiftwidth,tabstop call SetDynamicListChars()
    autocmd BufEnter,FileType * call SetDynamicListChars()
    autocmd VimEnter * nested call SetDynamicListChars()
augroup END

" Force run once immediately on Vim startup for the initial buffer
call SetDynamicListChars()

" Misc 
set nocompatible
set hlsearch
set showmode
let mapleader = " "
set clipboard=unnamedplus
set noswapfile
set relativenumber nu
set signcolumn=yes
set smartcase
set nowrap
set history=10000
if has('termguicolors') && empty($XDG_VTNR) && $TERM !=# 'linux'
	set termguicolors
endif


" Persistent undo
if has('persistent_undo')
    if !isdirectory(expand('~/.vim/undodir'))
        call mkdir(expand('~/.vim/undodir'), 'p', 0700)
    endif

    set undofile
    set undodir=~/.vim/undodir
    set undolevels=1000
endif


filetype plugin indent on
syntax on

nnoremap + *
nnoremap ö /
nnoremap ä ?

augroup cppman_lookup
    autocmd!
    autocmd FileType c,cpp setlocal keywordprg=cppman
augroup END

" Tab settings 
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4

" Ensure cursor is centered
augroup ForceScrolloff
    autocmd!
    autocmd BufEnter * set scrolloff=999
augroup END

" Bind reload vimrc
nnoremap <F12> :source /etc/vimrc<CR>

" ! Make sure, nodejs, npm, clangd, universal-ctags  are installed
" sudo pacman -S nodejs npm clang universal-ctags
source /etc/vim/plug.vim
source /etc/vim/coc.vim
source /etc/vim/bex.vim

set background=dark

set runtimepath+=/etc/vim
source /etc/vim/colors/gruvbox.vim

" Completely disable Netrw
let g:loaded_netrw       = 1
let g:loaded_netrwPlugin = 1

augroup BexCustomExplorer
	autocmd!
	autocmd VimEnter * if isdirectory(expand('%:p')) | call s:LoadBexExplorer() | endif
augroup END

function! s:LoadBexExplorer()
    let l:dir = expand('%:p')
    " Wipe the empty, dummy Netrw/Directory placeholder buffer safely
    let l:dummy_buf = bufnr('%')
    setlocal buftype=nofile bufhidden=wipe noswapfile
    execute 'Bex ' . fnameescape(l:dir)
    " Clean up the trailing empty buffer references if needed
    if bufexists(l:dummy_buf) | execute 'bwipeout ' . l:dummy_buf | endif
endfunction

nnoremap <leader>e :Bex<CR>
nnoremap <leader>w :ClangdManager<CR>

let g:ale_linters = {
\   'cpp': ['clangd'],
\   'c': ['clangd'],
\}

" Page navigation
nnoremap <PageDown> <C-d>
nnoremap <PageUp> <C-u>
inoremap <PageDown> <C-o><C-d>
inoremap <PageUp> <C-o><C-u>
vnoremap <PageDown> <C-d>
vnoremap <PageUp> <C-u>

" --- Fuzzy find --- 
nnoremap <C-p> :Files<CR>
nnoremap <C-b> :Buffers<CR>
nnoremap <C-t> :Tags<CR>
