" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimfiles/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim80/vimrc_example.vim or the vim manual
" and configure vim to your own liking!

" do not load defaults if ~/.vimrc is missing
"let skip_defaults_vim=1

if has('gui_running')
	set guioptions -=m 
	set guioptions -=T
endif

" Misc 
set nocompatible
set hlsearch
set showmode
let mapleader = " "
set clipboard=unnamedplus
set noswapfile
set relativenumber nu
set signcolumn=yes
set ignorecase
set smartcase
set nowrap
set history=10000
set termguicolors
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set encoding=utf-8
filetype plugin indent on
syntax on

command! W execute 'silent! write !sudo tee % >/dev/null' | edit!
cnoreabbrev <expr> w getcmdtype() == ':' && getcmdline() ==# 'w' ? 'W' : 'w'

" Ensure cursor is centered
augroup ForceScrolloff
    autocmd!
    autocmd BufEnter * set scrolloff=999
augroup END

" Persistent undo
if has('persistent_undo')
    if !isdirectory(expand('~/.vim/undodir'))
        call mkdir(expand('~/.vim/undodir'), 'p', 0700)
    endif

    set undofile
    set undodir=~/.vim/undodir
    set undolevels=1000
endif

augroup cppman_lookup
    autocmd!
    autocmd FileType c,cpp setlocal keywordprg=cppman
augroup END

" ! Make sure, nodejs, npm, clangd, universal-ctags are installed
" sudo pacman -S nodejs npm clang universal-ctags
source /etc/vim/plug.vim
source /etc/vim/coc.vim
source /etc/vim/ale.vim
source /etc/vim/bex.vim

set runtimepath+=/etc/vim
source /etc/vim/colors/base16.vim


nnoremap <leader>e :Bex<CR>
nnoremap <leader>w :ClangdManager<CR>

" Page navigation
nnoremap <PageDown> <C-d>
nnoremap <PageUp> <C-u>
inoremap <PageDown> <C-o><C-d>
inoremap <PageUp> <C-o><C-u>
vnoremap <PageDown> <C-d>
vnoremap <PageUp> <C-u>

" Fuzzy find
nnoremap <C-p> :Files<CR>
nnoremap <C-b> :Buffers<CR>
nnoremap <C-t> :Tags<CR>

nnoremap <F12> :source /etc/vimrc<CR>


set list
function! SetDynamicListChars()
    if !&l:modifiable || filewritable(expand('%:p')) != 1
        setlocal nolist
        return
    endif

    setlocal list

    let l:sw = &shiftwidth == 0 ? &tabstop : &shiftwidth
    let &l:listchars = 'trail:·,tab:│ ,multispace:┆' . repeat(' ', l:sw - 1)
endfunction

augroup DynamicListChars
    autocmd!
    autocmd OptionSet shiftwidth,tabstop call SetDynamicListChars()
    autocmd BufEnter,FileType * call SetDynamicListChars()
    autocmd VimEnter * nested call SetDynamicListChars()
augroup END
