# Auto-install TPM if not present
#if-shell "test ! -d ~/.tmux/plugins/tpm" \
#   "run-shell 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm'"

set-option -g status-position top

set -g status-interval 1
set -g status-left ''
set -g window-status-format '#I:#W'
set -g window-status-current-format '#I:#W'
set -g status-right-length 200
# Show path, time and date
set -g status-right '#[fg=brightyellow]#(echo "#{pane_current_path}" | sed "s|$HOME|~|") #[fg=brightblack]| #[fg=brightcyan]#(sed -n "1p" /sys/class/tty/tty0/active) #[fg=brightblack]| #[fg=brightyellow]%H:%M %a %d/%m/%y'

set -g prefix C-s
unbind C-b
bind C-s send-prefix

# Status bar background and foreground
set -g status-bg black
set -g mode-style bg=#243142,fg=White

unbind -T prefix Space

set -g window-status-style fg=brightblack
set -g window-status-current-style fg=brightyellow,,bold

# Window/pane base index set -g base-index 1 setw -g pane-base-index 1
set -g base-index 1
setw -g pane-base-index 1

# Alt+number window switching
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# In ~/.tmux.conf
set -g extended-keys always
set -ga terminal-features '*alacritty*:extkeys'
set -g extended-keys-format csi-u   

source-file /etc/tmux/vi.conf

# Bind user keys to window selection (User0 = first key, etc.)
bind -n C-1 select-window -t :1
bind -n C-2 select-window -t :2
bind -n C-3 select-window -t :3
bind -n C-4 select-window -t :4
bind -n C-5 select-window -t :5
bind -n C-6 select-window -t :6
bind -n C-7 select-window -t :7
bind -n C-8 select-window -t :8
bind -n C-9 select-window -t :9

# Initialize TPM (must be last line)
#run '~/.tmux/plugins/tpm/tpm'
